// Trident v0.12.0 harness entry  - generated by cf-invariants-anchor-emit
// for program `collateral_mint_ref`. Additive-only.
//
// Wording note: Trident already ships invariant / stateful fuzzing for
// Solana. This crate does NOT ship a fuzzer; it exposes the curated
// class-shaped `#[flow]` methods so `trident fuzz` picks them up.

#![allow(unused_imports)]

use trident_fuzz::prelude::*;

pub mod flows {
pub mod invariant_collateral_authority;
}
